[package]
name = "datafusion-benchmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
datafusion = "39.0.0"
serde = { version = "1.0.203", features = ["derive"] }
structopt = "0.3.26"
tokio = {  version = "1.38.0", features = ["rt-multi-thread"] }
serde_json = "1.0.117"